export enum RequestTypes {
    LOGIN_USER = "LOGIN_USER",
    LOGOUT_USER = "LOGOUT_USER",
    ADD_PRODUCT = "ADD_PRODUCT",
    LIST_PRODUCTS = "LIST_PRODUCTS",
    EDIT_PRODUCT = "EDIT_PRODUCT",
    GET_PRODUCT = "GET_PRODUCT"
}