export enum ActionTypes {
    USER_LOGED_IN = "USER_LOGED_IN",
    PRODUCT_LIST = "PRODUCT_LIST",
    PRODUCT_EDIT = "PRODUCT_EDIT",
    PRODUCT_DELETED = "PRODUCT_DELETED",
    REDIRECT = "REDIRECT",
    CLEAR_REDIRECT = "CLEAR_REDIRECT"
}