export enum ActionTypes {
    USER_LOGED_IN = "USER_LOGED_IN",
    PRODUCT_LIST = "PRODUCT_LIST",
    EDITING_PRODUCT = "EDITING_PRODUCT",
    REDIRECT = "REDIRECT",
    CLEAR_REDIRECT = "CLEAR_REDIRECT"
}